# fmt: yaml
# Inventory created with love by Limbail (limbail.com)
#
# - name inside "hosts" must be unique.
#   hosts:
#     NPL_001:
# - host_dict must be dictionary representation:
#   {'name': 'limbail', 'inner': {'item1':'1', 'item2':'2'}}

all:
    children:
# BEGIN - development
        development:
            children:
                dev_abap:
                    hosts:
                        NPL_001:
                            ansible_host: 192.168.50.179
                            host_dict: {'isbusiness_time': {'start': '08:00:00', 'end': '22:00:00'}, 'fqdn': '192.168.50.179', 'sap_sid': 'NPL', 'sap_client': '001', 'sap_sysn': '001', 'environment': 'dev', 'product_type': 'abap', 'db_type': 'sybase', 'urls': "http://localhost:8086/"}

                        HPL_001:
                            ansible_host: 192.168.50.179
                            host_dict: {'isbusiness_time': {'start': '08:00:00', 'end': '18:00:00'}, 'fqdn': '192.168.50.179', 'sap_sid': 'HPL', 'sap_client': '001', 'sap_sysn': '001', 'environment': 'dev', 'product_type': 'database', 'db_type': 'hana', 'urls': "http://localhost:8086/"}
                dev_java:
                    hosts:
                        NPB_001:
                            ansible_host: 192.168.50.179
                            host_dict: {'isbusiness_time': {'start': '08:00:00', 'end': '18:00:00'}, 'fqdn': '192.168.50.179', 'sap_sid': 'NPB', 'sap_client': '000', 'sap_sysn': '000', 'environment': 'dev', 'product_type': 'java', 'db_type': 'sybase', 'urls': "http://localhost:8086/signin,http://localhost:3000/login"}
                dev_webdisp:
                    hosts:
                        NPC_001:
                            ansible_host: 192.168.50.171
                            host_dict: {'isbusiness_time': {'start': '08:00:00', 'end': '18:00:00'}, 'fqdn': '192.168.50.171', 'sap_sid': 'NPC', 'sap_client': '000', 'sap_sysn': '000', 'environment': 'dev', 'product_type': 'webdisp', 'db_type': 'n/a', 'urls': "http://localhost:8086/"}

# BEGIN - preproduction:
        preproduction:
            children:
                pre_abap:
                    hosts:
                        IPL_001:
                            ansible_host: 192.168.50.179
                            host_dict: {'isbusiness_time': {'start': '08:00:00', 'end': '18:00:00'}, 'fqdn': '192.168.50.179', 'sap_sid': 'IPL', 'sap_client': '001', 'sap_sysn': '001', 'environment': 'pre', 'product_type': 'abap', 'db_type': 'sybase', 'urls': "https://expired.badssl.com/"}
                pre_java:
                    hosts:
                        IPB_001:
                            ansible_host: 192.168.50.171
                            host_dict: {'isbusiness_time': {'start': '08:00:00', 'end': '18:00:00'}, 'fqdn': '192.168.50.171', 'sap_sid': 'IPB', 'sap_client': '000', 'sap_sysn': '000', 'environment': 'pre', 'product_type': 'java', 'db_type': 'sybase', 'urls': "http://localhost:8086/,https://expired.badssl.com/"}
                pre_webdisp:
                    hosts:
                        IPC_001:
                            ansible_host: 192.168.50.171
                            host_dict: {'isbusiness_time': {'start': '08:00:00', 'end': '18:00:00'}, 'fqdn': '192.168.50.171', 'sap_sid': 'IPC', 'sap_client': '000', 'sap_sysn': '000', 'environment': 'pre', 'product_type': 'webdisp', 'db_type': 'n/a', 'urls': "https://expired.badssl.com/"}
# BEGIN - production:
        production:
            children:
                pro_abap:
                    hosts:
                        PPL_001:
                            ansible_host: 192.168.50.179
                            host_dict: {'isbusiness_time': {'start': '08:00:00', 'end': '18:00:00'}, 'fqdn': '192.168.50.179', 'sap_sid': 'PPL', 'sap_client': '001', 'sap_sysn': '001', 'environment': 'pre', 'product_type': 'abap', 'db_type': 'sybase', 'urls': "http://localhost:8086/"}
                pro_java:
                    hosts:
                        PPB_001:
                            ansible_host: 192.168.50.171
                            host_dict: {'isbusiness_time': {'start': '08:00:00', 'end': '18:00:00'}, 'fqdn': '192.168.50.171', 'sap_sid': 'PPB', 'sap_client': '000', 'sap_sysn': '000', 'environment': 'pre', 'product_type': 'java', 'db_type': 'sybase', 'urls': "https://asdddddddssl.com/,https://expired.badssl.com/"}
                pro_webdisp:
                    hosts:
                        PPC_001:
                            ansible_host: 192.168.50.171
                            host_dict: {'isbusiness_time': {'start': '08:00:00', 'end': '18:00:00'}, 'fqdn': '192.168.50.171', 'sap_sid': 'PPC', 'sap_client': '000', 'sap_sysn': '000', 'environment': 'pre', 'product_type': 'webdisp', 'db_type': 'n/a', 'urls': "http://localhost:8086/"}
    vars:
        ansible_python_interpreter: /usr/bin/env python
        #ansible_python_interpreter: /usr/bin/python